package capuli.dominino;
// Generated 20/09/2016 12:09:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bebida generated by hbm2java
 */
@Entity
@Table(name="bebida"
    ,catalog="sgr"
)
public class Bebida  implements java.io.Serializable {


     private Integer idBebida;
     private String nombre;
//     private Set<Menu> menus = new HashSet<Menu>(0);

    public Bebida() {
    }

    public Bebida(String nombre) {
       this.nombre = nombre;
//       this.menus = menus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_BEBIDA", unique=true, nullable=false)
    public Integer getIdBebida() {
        return this.idBebida;
    }
    
    public void setIdBebida(Integer idBebida) {
        this.idBebida = idBebida;
    }

    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="bebida")
//    public Set<Menu> getMenus() {
//        return this.menus;
//    }
//    
//    public void setMenus(Set<Menu> menus) {
//        this.menus = menus;
//    }

    @Override
    public String toString() {
        return "Bebida{"  + nombre + '}';
    }




}


