package capuli.dominino;
// Generated 20/09/2016 12:09:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comensal generated by hbm2java
 */
@Entity
@Table(name="comensal"
    ,catalog="sgr"
)
public class Comensal  implements java.io.Serializable {


     private Integer idComensal;
     private Empresa empresa;
     private String nombres;
     private String apellidos;
     private String telefono;
     private byte[] foto;
     private String dni;
     private String usuario;
     private String contrasena;
     private Set<Pedido> pedidos = new HashSet<Pedido>(0);
     private Set<ListNocturno> listNocturnos = new HashSet<ListNocturno>(0);

    public Comensal() {
    }

    public Comensal(Empresa empresa, String nombres, String apellidos, String telefono, byte[] foto, String dni, String usuario, String contrasena, Set<Pedido> pedidos, Set<ListNocturno> listNocturnos) {
       this.empresa = empresa;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.telefono = telefono;
       this.foto = foto;
       this.dni = dni;
       this.usuario = usuario;
       this.contrasena = contrasena;
       this.pedidos = pedidos;
       this.listNocturnos = listNocturnos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_COMENSAL", unique=true, nullable=false)
    public Integer getIdComensal() {
        return this.idComensal;
    }
    
    public void setIdComensal(Integer idComensal) {
        this.idComensal = idComensal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="EMPRESA_ID_EMPRESA")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="NOMBRES", length=50)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="APELLIDOS", length=50)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="TELEFONO", length=10)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="FOTO")
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    
    @Column(name="DNI", length=8)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="USUARIO", length=50)
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="CONTRASENA", length=200)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comensal")
    public Set<Pedido> getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set<Pedido> pedidos) {
        this.pedidos = pedidos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comensal")
    public Set<ListNocturno> getListNocturnos() {
        return this.listNocturnos;
    }
    
    public void setListNocturnos(Set<ListNocturno> listNocturnos) {
        this.listNocturnos = listNocturnos;
    }

//    @Override
    public String enCadena() {
        return "Comensal{" + "idComensal=" + idComensal + ", empresa=" + empresa + ", nombres=" + nombres + ", apellidos=" + apellidos + ", telefono=" + telefono + ", foto=" + foto + ", dni=" + dni + ", usuario=" + usuario + ", contrasena=" + contrasena +  '}';
    }




}


