package capuli.dominino;
// Generated 20/09/2016 12:09:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entrada generated by hbm2java
 */
@Entity
@Table(name="entrada"
    ,catalog="sgr"
)
public class Entrada  implements java.io.Serializable {


     private Integer idEntrada;
     private String nombre;
//     private Set<Menu> menus = new HashSet<Menu>(0);

    public Entrada() {
    }

    public Entrada(String nombre/*, Set<Menu> menus*/) {
       this.nombre = nombre;
//       this.menus = menus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_ENTRADA", unique=true, nullable=false)
    public Integer getIdEntrada() {
        return this.idEntrada;
    }
    
    public void setIdEntrada(Integer idEntrada) {
        this.idEntrada = idEntrada;
    }

    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="entrada")
//    public Set<Menu> getMenus() {
//        return this.menus;
//    }
//    
//    public void setMenus(Set<Menu> menus) {
//        this.menus = menus;
//    }

    @Override
    public String toString() {
        return "Entrada{" + nombre + '}';
    }




}


