package capuli.dominino;
// Generated 20/09/2016 12:09:12 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name="pedido"
    ,catalog="sgr"
)
public class Pedido  implements java.io.Serializable {


     private Integer idPedido;
     private Comensal comensal;
     private Menu menu;
     private Integer numMesa;
     private Integer cantidad;
     private Byte precioUnt;
     private Byte precioTotal;
     private Date fecha;

    public Pedido() {
    }

	
    public Pedido(Comensal comensal) {
        this.comensal = comensal;
    }
    public Pedido(Comensal comensal, Menu menu, Integer numMesa, Integer cantidad, Byte precioUnt, Byte precioTotal, Date fecha) {
       this.comensal = comensal;
       this.menu = menu;
       this.numMesa = numMesa;
       this.cantidad = cantidad;
       this.precioUnt = precioUnt;
       this.precioTotal = precioTotal;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_PEDIDO", unique=true, nullable=false)
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="COMENSALES_ID_COMENSAL", nullable=false)
    public Comensal getComensal() {
        return this.comensal;
    }
    
    public void setComensal(Comensal comensal) {
        this.comensal = comensal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MENU_ID_MENU")
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    
    @Column(name="NUM_MESA")
    public Integer getNumMesa() {
        return this.numMesa;
    }
    
    public void setNumMesa(Integer numMesa) {
        this.numMesa = numMesa;
    }

    
    @Column(name="CANTIDAD")
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="PRECIO_UNT", precision=2, scale=0)
    public Byte getPrecioUnt() {
        return this.precioUnt;
    }
    
    public void setPrecioUnt(Byte precioUnt) {
        this.precioUnt = precioUnt;
    }

    
    @Column(name="PRECIO_TOTAL", precision=2, scale=0)
    public Byte getPrecioTotal() {
        return this.precioTotal;
    }
    
    public void setPrecioTotal(Byte precioTotal) {
        this.precioTotal = precioTotal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FECHA", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


