package capuli.dominino;
// Generated 20/09/2016 12:09:12 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoMenu generated by hbm2java
 */
@Entity
@Table(name="tipo_menu"
    ,catalog="sgr"
)
public class TipoMenu  implements java.io.Serializable {


     private Integer idTipo;
     private String nombre;
//     private Set<Menu> menus = new HashSet<Menu>(0);

    public TipoMenu() {
    }

    public TipoMenu(String nombre/*, Set<Menu> menus*/) {
       this.nombre = nombre;
//       this.menus = menus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_TIPO", unique=true, nullable=false)
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }

    
    @Column(name="NOMBRE", length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoMenu")
//    public Set<Menu> getMenus() {
//        return this.menus;
//    }
//    
//    public void setMenus(Set<Menu> menus) {
//        this.menus = menus;
//    }

    @Override
    public String toString() {
        return "TipoMenu{"  + nombre + '}';
    }




}


